services: 
  db:
    image: postgres
    restart: always
    volumes:
    - ./data/db:/var/lib/postgresql/data
    environment:
    - POSTGRES_DB=tripplanner
    - POSTGRES_USER=tripplanner
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  web: 
    build: .
    ports: 
      - '8000:8000'
    volumes:
    - .:/opt/trip-planner
    depends_on:
    - db